### ISSUE TITLE
Error with last version mailcatcher 0.9

### ISSUE THREAD

**Issue by nerlijman** [spaquet/docker-alpine-mailcatcher#12]
Just tried the last version and I have this error. I am on M1 apple processor. Non M1 version does work fine.
The docker tags with mailcatcher  0.8 are not available anymore?

`docker run --rm -p 1080:1080 -p 1025:1025 --name mailcatcher stpaquet/alpinemailcatcher`

`
Unable to find image 'stpaquet/alpinemailcatcher:latest' locally
latest: Pulling from stpaquet/alpinemailcatcher
579b34f0a95b: Already exists
b86f46128203: Pull complete
Digest: sha256:f12571ea5e2dd27af08c8fcfd025678565a584c9130a064ad089e7e144e9047d
Status: Downloaded newer image for stpaquet/alpinemailcatcher:latest
Starting MailCatcher v0.9.0
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.6-aarch64-linux/lib/sqlite3.rb:6:in 'rescue in <top (required)>'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.6-aarch64-linux/lib/sqlite3.rb:2:in '<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in '<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in '<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in 'block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in 'rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in 'block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in 'run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in 'run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in 'run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in '<top (required)>'
	from /usr/bin/mailcatcher:25:in 'load'
	from /usr/bin/mailcatcher:25:in '<main>
'
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require': Error relocating /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.6-aarch64-linux/lib/sqlite3/3.2/sqlite3_native.so: fcntl64: symbol not found - /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.6-aarch64-linux/lib/sqlite3/3.2/sqlite3_native.so (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.6-aarch64-linux/lib/sqlite3.rb:4:in '<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in '<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in '<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in 'require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in 'block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in 'rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in 'block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in 'run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in 'run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in 'run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in '<top (required)>'
	from /usr/bin/mailcatcher:25:in 'load'
	from /usr/bin/mailcatcher:25:in '<main>''
`

**Comment by nerlijman** [comment]
Version with v0.8.2 work fine with M1.

**Comment by spaquet** [comment]
@nerlijman thanks for reporting. We actually pin point the issue and a new version should being released soon.

**Comment by spaquet** [comment]
Fixed in version 1.8.3
Version 1.8.0 is just kept for reference but must not be used.
